# Generated by Django 4.2.10 on 2024-05-16 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('monto', models.PositiveBigIntegerField()),
                ('monto_original', models.PositiveBigIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('cantidad', models.PositiveBigIntegerField()),
                ('precio_unitario', models.PositiveBigIntegerField()),
                ('descripcion', models.TextField()),
                ('iva', models.BooleanField()),
                ('subtotal', models.PositiveBigIntegerField(blank=True, null=True)),
                ('total', models.PositiveBigIntegerField(blank=True, null=True)),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.presupuesto')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
