# Generated by Django 4.2.10 on 2024-05-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_factura_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='presupuesto_id',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
