# Generated by Django 4.2.10 on 2024-05-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_presupuesto_presupuesto_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='cantidad',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='factura',
            name='precio_unitario',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='factura',
            name='subtotal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='monto',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='monto_original',
            field=models.FloatField(),
        ),
    ]
