# Generated by Django 4.2.10 on 2024-05-21 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_presupuesto_en_linea_alter_presupuesto_aula_virtual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='s2_0700399A03',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='s2_0700399A31',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='s2_0705103A00',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='s2_0870399A06',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='s2_0875103A00',
            field=models.IntegerField(default=0),
        ),
    ]
