# Generated by Django 4.2.10 on 2024-05-23 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_presupuesto_s2_0700399a03_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='cesta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='folio_de_entrada',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='orden_de_compra',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
