# Generated by Django 4.2.10 on 2024-05-27 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_userareaorsubarea_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userareaorsubarea',
            name='puede_editar_monto',
            field=models.BooleanField(default=False),
        ),
    ]
